export const DELETE_JOB_APPLICATION = "DELETE_JOB_APPLICATION";
export const SELECT_JOB_APPLICATION = "SELECT_JOB_APPLICATION";
export const UPDATE_JOB_APPLICATION = "UPDATE_JOB_APPLICATION";
export const ADD_JOB_APPLICATION = "ADD_JOB_APPLICATION";
export const CLEAR_SELECTED_JOB_APPLICATION = "CLEAR_SELECTED_JOB_APPLICATION";
export const GET_JOB_APPLICATIONS = "GET_JOB_APPLICATIONS";
export const GET_TOTAL_JOB_APPLICATIONS = "GET_TOTAL_JOB_APPLICATIONS";
export const SET_ERROR = "SET_ERROR";
